/*
 * Minesweeper API
 * REST API for Minesweeper
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;
/**
 * BoardConfiguration
 */

public class BoardConfiguration {
  @SerializedName("rows")
  private Integer rows = null;

  @SerializedName("columns")
  private Integer columns = null;

  @SerializedName("mines")
  private Integer mines = null;

  public BoardConfiguration rows(Integer rows) {
    this.rows = rows;
    return this;
  }

   /**
   * Get rows
   * minimum: 2
   * maximum: 20
   * @return rows
  **/
  @Schema(description = "")
  public Integer getRows() {
    return rows;
  }

  public void setRows(Integer rows) {
    this.rows = rows;
  }

  public BoardConfiguration columns(Integer columns) {
    this.columns = columns;
    return this;
  }

   /**
   * Get columns
   * minimum: 2
   * maximum: 20
   * @return columns
  **/
  @Schema(description = "")
  public Integer getColumns() {
    return columns;
  }

  public void setColumns(Integer columns) {
    this.columns = columns;
  }

  public BoardConfiguration mines(Integer mines) {
    this.mines = mines;
    return this;
  }

   /**
   * Get mines
   * minimum: 1
   * @return mines
  **/
  @Schema(description = "")
  public Integer getMines() {
    return mines;
  }

  public void setMines(Integer mines) {
    this.mines = mines;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BoardConfiguration boardConfiguration = (BoardConfiguration) o;
    return Objects.equals(this.rows, boardConfiguration.rows) &&
        Objects.equals(this.columns, boardConfiguration.columns) &&
        Objects.equals(this.mines, boardConfiguration.mines);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rows, columns, mines);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BoardConfiguration {\n");
    
    sb.append("    rows: ").append(toIndentedString(rows)).append("\n");
    sb.append("    columns: ").append(toIndentedString(columns)).append("\n");
    sb.append("    mines: ").append(toIndentedString(mines)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
