/*
 * Minesweeper API
 * REST API for Minesweeper
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
/**
 * BoardDetails
 */

public class BoardDetails {
  @SerializedName("cells")
  private List<List<Integer>> cells = null;

  @SerializedName("stringRepresentation")
  private String stringRepresentation = null;

  public BoardDetails cells(List<List<Integer>> cells) {
    this.cells = cells;
    return this;
  }

  public BoardDetails addCellsItem(List<Integer> cellsItem) {
    if (this.cells == null) {
      this.cells = new ArrayList<List<Integer>>();
    }
    this.cells.add(cellsItem);
    return this;
  }

   /**
   * Get cells
   * @return cells
  **/
  @Schema(description = "")
  public List<List<Integer>> getCells() {
    return cells;
  }

  public void setCells(List<List<Integer>> cells) {
    this.cells = cells;
  }

  public BoardDetails stringRepresentation(String stringRepresentation) {
    this.stringRepresentation = stringRepresentation;
    return this;
  }

   /**
   * Get stringRepresentation
   * @return stringRepresentation
  **/
  @Schema(description = "")
  public String getStringRepresentation() {
    return stringRepresentation;
  }

  public void setStringRepresentation(String stringRepresentation) {
    this.stringRepresentation = stringRepresentation;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BoardDetails boardDetails = (BoardDetails) o;
    return Objects.equals(this.cells, boardDetails.cells) &&
        Objects.equals(this.stringRepresentation, boardDetails.stringRepresentation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cells, stringRepresentation);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BoardDetails {\n");
    
    sb.append("    cells: ").append(toIndentedString(cells)).append("\n");
    sb.append("    stringRepresentation: ").append(toIndentedString(stringRepresentation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
