/*
 * Minesweeper API
 * REST API for Minesweeper
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * BoardSummary
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-11-01T12:40:21.123600-03:00[America/Montevideo]")
public class BoardSummary {
  @SerializedName("uid")
  private String uid = null;

  @SerializedName("rows")
  private Integer rows = null;

  @SerializedName("columns")
  private Integer columns = null;

  @SerializedName("mines")
  private Integer mines = null;

  @SerializedName("isActive")
  private Boolean isActive = null;

  @SerializedName("isGameOver")
  private Boolean isGameOver = null;

  public BoardSummary uid(String uid) {
    this.uid = uid;
    return this;
  }

   /**
   * Get uid
   * @return uid
  **/
  @Schema(description = "")
  public String getUid() {
    return uid;
  }

  public void setUid(String uid) {
    this.uid = uid;
  }

  public BoardSummary rows(Integer rows) {
    this.rows = rows;
    return this;
  }

   /**
   * Get rows
   * @return rows
  **/
  @Schema(description = "")
  public Integer getRows() {
    return rows;
  }

  public void setRows(Integer rows) {
    this.rows = rows;
  }

  public BoardSummary columns(Integer columns) {
    this.columns = columns;
    return this;
  }

   /**
   * Get columns
   * @return columns
  **/
  @Schema(description = "")
  public Integer getColumns() {
    return columns;
  }

  public void setColumns(Integer columns) {
    this.columns = columns;
  }

  public BoardSummary mines(Integer mines) {
    this.mines = mines;
    return this;
  }

   /**
   * Get mines
   * @return mines
  **/
  @Schema(description = "")
  public Integer getMines() {
    return mines;
  }

  public void setMines(Integer mines) {
    this.mines = mines;
  }

  public BoardSummary isActive(Boolean isActive) {
    this.isActive = isActive;
    return this;
  }

   /**
   * Get isActive
   * @return isActive
  **/
  @Schema(description = "")
  public Boolean isIsActive() {
    return isActive;
  }

  public void setIsActive(Boolean isActive) {
    this.isActive = isActive;
  }

  public BoardSummary isGameOver(Boolean isGameOver) {
    this.isGameOver = isGameOver;
    return this;
  }

   /**
   * Get isGameOver
   * @return isGameOver
  **/
  @Schema(description = "")
  public Boolean isIsGameOver() {
    return isGameOver;
  }

  public void setIsGameOver(Boolean isGameOver) {
    this.isGameOver = isGameOver;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BoardSummary boardSummary = (BoardSummary) o;
    return Objects.equals(this.uid, boardSummary.uid) &&
        Objects.equals(this.rows, boardSummary.rows) &&
        Objects.equals(this.columns, boardSummary.columns) &&
        Objects.equals(this.mines, boardSummary.mines) &&
        Objects.equals(this.isActive, boardSummary.isActive) &&
        Objects.equals(this.isGameOver, boardSummary.isGameOver);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uid, rows, columns, mines, isActive, isGameOver);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BoardSummary {\n");
    
    sb.append("    uid: ").append(toIndentedString(uid)).append("\n");
    sb.append("    rows: ").append(toIndentedString(rows)).append("\n");
    sb.append("    columns: ").append(toIndentedString(columns)).append("\n");
    sb.append("    mines: ").append(toIndentedString(mines)).append("\n");
    sb.append("    isActive: ").append(toIndentedString(isActive)).append("\n");
    sb.append("    isGameOver: ").append(toIndentedString(isGameOver)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
