/*
 * Minesweeper API
 * REST API for Minesweeper
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;
/**
 * ErrorResponseError
 */

public class ErrorResponseError {
  @SerializedName("requestId")
  private Integer requestId = null;

  @SerializedName("message")
  private String message = null;

  public ErrorResponseError requestId(Integer requestId) {
    this.requestId = requestId;
    return this;
  }

   /**
   * Number to identify the request
   * @return requestId
  **/
  @Schema(description = "Number to identify the request")
  public Integer getRequestId() {
    return requestId;
  }

  public void setRequestId(Integer requestId) {
    this.requestId = requestId;
  }

  public ErrorResponseError message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Description of the error
   * @return message
  **/
  @Schema(description = "Description of the error")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ErrorResponseError errorResponseError = (ErrorResponseError) o;
    return Objects.equals(this.requestId, errorResponseError.requestId) &&
        Objects.equals(this.message, errorResponseError.message);
  }

  @Override
  public int hashCode() {
    return Objects.hash(requestId, message);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ErrorResponseError {\n");
    
    sb.append("    requestId: ").append(toIndentedString(requestId)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
