/*
 * Minesweeper API
 * REST API for Minesweeper
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;
/**
 * PlayerMove
 */

public class PlayerMove {
  @SerializedName("moveType")
  private PlayerMoveType moveType = null;

  @SerializedName("coordinates")
  private Coordinates coordinates = null;

  public PlayerMove moveType(PlayerMoveType moveType) {
    this.moveType = moveType;
    return this;
  }

   /**
   * Get moveType
   * @return moveType
  **/
  @Schema(description = "")
  public PlayerMoveType getMoveType() {
    return moveType;
  }

  public void setMoveType(PlayerMoveType moveType) {
    this.moveType = moveType;
  }

  public PlayerMove coordinates(Coordinates coordinates) {
    this.coordinates = coordinates;
    return this;
  }

   /**
   * Get coordinates
   * @return coordinates
  **/
  @Schema(description = "")
  public Coordinates getCoordinates() {
    return coordinates;
  }

  public void setCoordinates(Coordinates coordinates) {
    this.coordinates = coordinates;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlayerMove playerMove = (PlayerMove) o;
    return Objects.equals(this.moveType, playerMove.moveType) &&
        Objects.equals(this.coordinates, playerMove.coordinates);
  }

  @Override
  public int hashCode() {
    return Objects.hash(moveType, coordinates);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlayerMove {\n");
    
    sb.append("    moveType: ").append(toIndentedString(moveType)).append("\n");
    sb.append("    coordinates: ").append(toIndentedString(coordinates)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
