/*
 * Minesweeper API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.BoardConfiguration;
import io.swagger.client.model.BoardDetails;
import io.swagger.client.model.BoardSummary;
import io.swagger.client.model.ErrorResponse;
import io.swagger.client.model.PlayerMove;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for GamesApi
 */
@Ignore
public class GamesApiTest {

    private final GamesApi api = new GamesApi();

    /**
     * Create a new board for the logged in user
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createBoardTest() throws ApiException {
        BoardConfiguration body = null;
        BoardSummary response = api.createBoard(body);

        // TODO: test validations
    }
    /**
     * Make a move
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void moveTest() throws ApiException {
        PlayerMove body = null;
        String boardUid = null;
        BoardDetails response = api.move(body, boardUid);

        // TODO: test validations
    }
    /**
     * Get all boards for the logged in user
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void retrieveAllBoardsTest() throws ApiException {
        List<BoardSummary> response = api.retrieveAllBoards();

        // TODO: test validations
    }
    /**
     * Get details of a board
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void retrieveBoardTest() throws ApiException {
        String boardUid = null;
        BoardDetails response = api.retrieveBoard(boardUid);

        // TODO: test validations
    }
    /**
     * Change preserved/active board status
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void setBoardIsActiveTest() throws ApiException {
        Boolean body = null;
        String boardUid = null;
        BoardSummary response = api.setBoardIsActive(body, boardUid);

        // TODO: test validations
    }
}
